// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/exxampl.proto

package exxampl

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v3/api"
	client "github.com/micro/go-micro/v3/client"
	server "github.com/micro/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Exxampl service

func NewExxamplEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Exxampl service

type ExxamplService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Exxampl_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Exxampl_PingPongService, error)
}

type exxamplService struct {
	c    client.Client
	name string
}

func NewExxamplService(name string, c client.Client) ExxamplService {
	return &exxamplService{
		c:    c,
		name: name,
	}
}

func (c *exxamplService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Exxampl.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exxamplService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Exxampl_StreamService, error) {
	req := c.c.NewRequest(c.name, "Exxampl.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &exxamplServiceStream{stream}, nil
}

type Exxampl_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type exxamplServiceStream struct {
	stream client.Stream
}

func (x *exxamplServiceStream) Close() error {
	return x.stream.Close()
}

func (x *exxamplServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *exxamplServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *exxamplServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *exxamplServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exxamplService) PingPong(ctx context.Context, opts ...client.CallOption) (Exxampl_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Exxampl.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &exxamplServicePingPong{stream}, nil
}

type Exxampl_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type exxamplServicePingPong struct {
	stream client.Stream
}

func (x *exxamplServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *exxamplServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *exxamplServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *exxamplServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *exxamplServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *exxamplServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Exxampl service

type ExxamplHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Exxampl_StreamStream) error
	PingPong(context.Context, Exxampl_PingPongStream) error
}

func RegisterExxamplHandler(s server.Server, hdlr ExxamplHandler, opts ...server.HandlerOption) error {
	type exxampl interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Exxampl struct {
		exxampl
	}
	h := &exxamplHandler{hdlr}
	return s.Handle(s.NewHandler(&Exxampl{h}, opts...))
}

type exxamplHandler struct {
	ExxamplHandler
}

func (h *exxamplHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ExxamplHandler.Call(ctx, in, out)
}

func (h *exxamplHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ExxamplHandler.Stream(ctx, m, &exxamplStreamStream{stream})
}

type Exxampl_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type exxamplStreamStream struct {
	stream server.Stream
}

func (x *exxamplStreamStream) Close() error {
	return x.stream.Close()
}

func (x *exxamplStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *exxamplStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *exxamplStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *exxamplStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *exxamplHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ExxamplHandler.PingPong(ctx, &exxamplPingPongStream{stream})
}

type Exxampl_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type exxamplPingPongStream struct {
	stream server.Stream
}

func (x *exxamplPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *exxamplPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *exxamplPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *exxamplPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *exxamplPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *exxamplPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
